language: php

php:
- 5.3
- 5.4
- 5.5
- 5.6
- 7.0

install:
- composer self-update
- composer install --ignore-platform-reqs
- npm install
- npm install --global grunt-cli

script:
- npm test
- npm run phpunit

after_script:
- php vendor/bin/coveralls --verbose
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover clover.xml

notifications:
 irc:
  - chat.freenode.net#redaxscript
 webhooks:
  - https://webhooks.gitter.im/e/ff9acda2e5faf42e3182
